NewsPaper/NewsPaper/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

from sign.views import upgrade_me

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('posts/', include('news.urls')),
    path('news/', include('news.urls')),
    path('', include('protect.urls')),
    path('sign/', include('sign.urls')),
    path('accounts/', include('allauth.urls')),
]

NewsPaper/news/urls.py

from django.urls import path

from sign.views import upgrade_me
from .views import NewsList, NewsDetail, NewsSearch, NewsCreate, NewsUpdate, NewsDelete, ArticlesUpdate, ArticlesDelete, \
    CategoryListView, subscribe

urlpatterns = [
    path('', NewsList.as_view(), name='post_list'),
    path('<int:pk>/', NewsDetail.as_view(), name='post_detail'),
    path('search/', NewsSearch.as_view(), name='post_search'),
    path('create/', NewsCreate.as_view(), name='news_create'),
    path('<int:pk>/edit/', NewsUpdate.as_view(), name='news_edit'),
    path('<int:pk>/delete/', NewsDelete.as_view(), name='news_delete'),
    path('articles/create/', NewsCreate.as_view(), name='articles_create'),
    path('articles/<int:pk>/edit/', ArticlesUpdate.as_view(), name='articles_edit'),
    path('articles/<int:pk>/delete/', ArticlesDelete.as_view(), name='articles_delete'),
    path('upgrade/', upgrade_me, name='upgrade'),
    path('categories/<int:pk>', CategoryListView.as_view(), name='category_list'),
    path('categories/<int:pk>/subscribe', subscribe, name='subscribe'),
]

NewsPaper/news/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Sum
from django.db.models.functions import Coalesce
from django.template.backends import django
from django.urls import reverse


class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='Имя')
    rating = models.IntegerField(default=0)

    def update_rating(self):
        posts_rating = Post.objects.filter(author=self).aggregate(pr=Coalesce(Sum('rating'), 0))['pr']
        comments_rating = Comment.objects.filter(user=self.user).aggregate(cr=Coalesce(Sum('rating'), 0))['cr']
        posts_comments_rating = Comment.objects.filter(post__author=self).aggregate(pcr=Coalesce(Sum('rating'), 0))[
            'pcr']
        self.rating = posts_rating * 3 + comments_rating + posts_comments_rating
        self.save()


class Category(models.Model):
    name = models.CharField(max_length=25, unique=True, verbose_name='Категории')
    subscribers = models.ManyToManyField(User, blank=True, related_name='categories')

    def __str__(self):
        return self.name


class Post(models.Model):
    news = 'NE'
    article = 'AR'

    POST_TYPES = [
        (news, "Новость"),
        (article, 'Статья'),
    ]

    post_time = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    title = models.CharField(max_length=255, verbose_name="Заголовок")
    text = models.TextField()
    post_type = models.CharField(max_length=2, choices=POST_TYPES, default=news, verbose_name="Вид поста")
    author = models.ForeignKey(Author, on_delete=models.CASCADE, verbose_name="Автор")
    post_update = models.DateTimeField(auto_now=True, verbose_name="Дата изменения")
    rating = models.IntegerField(default=0)
    category = models.ManyToManyField(Category, through='PostCategory', verbose_name="Категория")

    def preview(self):
        return f"{self.text[:124]}..."

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def __str__(self):
        return f'id-{self.pk}: {self.title}'

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])


class PostCategory(models.Model):
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name="Пост")
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Пользователь")
    date_in = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    text = models.TextField()
    rating = models.IntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

NewsPaper/templates/articles_create.html
{% extends 'default.html' %}

{% block content %}
<h1>Добавление статьи</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

NewsPaper/templates/articles_delete.html
{% extends 'default.html' %}

{% block content %}
<h1>Удаление статьи</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.title }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

NewsPaper/templates/articles_edit.html
{% extends 'default.html' %}

{% block content %}
<h1>Редактирование статьи</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

NewsPaper/templates/category_list.html

{% extends 'default.html' %}

{% load custom_filters %}

{% block content %}

    {% if is_not_subscriber %}
        <p class="text-center"><a href="{% url 'subscribe' category.id %}" class="btn btn-secondary btn-sm">Подписаться</a> </p>
    {% endif %}

    <hr>
    <form action="" method="get">
    {{ filterset.form.as_p }}
        <input type="submit" value="Найти">
    </form>


{% if category_news_list %}

<table width="100%" style="margin-top:35px">
    <tr>
        <td><u>Категория</u></td>
        <td><u>Заголовок</u></td>
        <td><u>Содержание</u></td>
        <td><u>Дата публикации</u></td>
    </tr>
    {% for post in category_news_list %}
    <tr>
        <td>
            {% for category in post.category.all %}
                <a href="{% url 'category_list' category.id %}">{{ category }}</a>
            {% endfor %}
        </td>
        <td>{{ post.title }}</td>
        <td>{{ post.text|truncatewords:20|censor }}</td>
        <td>{{ post.post_time|date:'d M Y' }}</td>
    </tr>
    {% endfor %}
</table>
{% else %}
<h3>Публикаций нет!</h3>
{% endif %}
{% if page_obj.has_previous %}
    <a href="?page=1">1</a>
    {% if page_obj.previous_page_number != 1 %}
        ...
        <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
    {% endif %}
{% endif %}
{{ page_obj.number }}
{% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
        {% if paginator.num_pages != page_obj.next_page_number %}
            ...
            <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
        {% endif %}
{% endif %}


{% endblock content %}

NewsPaper/templates/daily_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Уведомление</title>

</head>

<body>
    <h2>Здравствуйте! Новые статьи за последнюю неделю</h2>
    <ul>
        {% for post in posts %}
        <li><a href ="{{ link }}{{ post.get_absolute_url }}">{{ post.title }}</a></li>
        {%endfor%}
    </ul>

</body>
</html>

NewsPaper/templates/default.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>
    <h1>Заголовок</h1>
    </title>
    {% load static %}

    <link href="{% static 'css/styles.css' %}" rel="stylesheet"/>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
    <div class="container">
        <a class="navbar-brand" href="/home/">News Portal</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Все новости</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Поиск новостей</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Добавление новостей</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    <div class="row">
        <div class="col-lg-12 text-center">
            {% block content %}

            {% endblock content %}
        </div>
    </div>
</div>
</body>
</html>

NewsPaper/templates/main.html
<html>
    <head>
        <title> Simple SignUp/SignIn app</title>
    </head>
    <body>
        <div>
            <h1><a href="/">Simple SignUp/SignIn app</a></h1>
        </div>
        {% block content %}
        {% endblock %}
    </body>
</html>

NewsPaper/templates/monday_letters.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Уведомление</title>

</head>

<body>
<h2>Здравствуйте! Новые статьи за последнюю неделю</h2>
<ul>
    {% for post in posts %}
    <li><a href ="{{link}}{{post.get_absolute_url}}">{{post.title}}</a></li>
    {%endfor%}
</ul>

</body>
</html>

NewsPaper/templates/news_delete.html
{% extends 'default.html' %}

{% block content %}
<h1>Удаление новости</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.title }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

NewsPaper/templates/news_edit.html
{% extends 'default.html' %}

{% block content %}
<h1>Редактирование новости</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

NewsPaper/templates/post_created_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Уведомление</title>
</head>
<body>
    <h2>Здравствуйте! Новая <a href = "{{ link }}"> статья </a> в вашем любимом разделе!</h2>
        <p>{{ text }}</p>
</body>
</html>

NewsPaper/templates/post_detail.html

{% extends "default.html" %}

{% load custom_filters %}


{% block content %}
{% if post %}
<table>
    <tr>
        <td>Заголовок</td>
        <td>Содержание</td>
        <td>Дата публикации</td>
    </tr>
    <tr>
        <td>{{ post.title }}</td>
        <td>{{ post.text|censor }}</td>
        <td>{{ post.post_time|date:'d M Y' }}</td>
    </tr>
</table>
{% else %}
<h3>Публикаций нет!</h3>
{% endif %}
{% endblock content %}

NewsPaper/templates/post_list.html

{% extends 'default.html' %}

{% load custom_filters %}

{% block content %}
{% if posts %}
    <h2>Количество постов: {{ posts|length }}</h2>
<table width="100%" style="margin-top:35px">
    <tr>
        <td><u>Категория</u></td>
        <td><u>Заголовок</u></td>
        <td><u>Содержание</u></td>
        <td><u>Дата публикации</u></td>
        <td><u>Тип публикации</u></td>
    </tr>
    {% for post in posts %}
    <tr>
        <td>
            {% for category in post.category.all %}
                <a href="{% url 'category_list' category.id %}">{{ category }}</a>
            {% endfor %}
        </td>
        <td>{{ post.title }}</td>
        <td>{{ post.text|truncatewords:20|censor }}</td>
        <td>{{ post.post_time|date:'d M Y' }}</td>
        <td>{{ post.get_post_type_display }}</td>
    </tr>
    {% endfor %}
</table>
{% else %}
<h3>Публикаций нет!</h3>
{% endif %}
{% if page_obj.has_previous %}
    <a href="?page=1">1</a>
    {% if page_obj.previous_page_number != 1 %}
        ...
        <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
    {% endif %}
{% endif %}
{{ page_obj.number }}
{% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
        {% if paginator.num_pages != page_obj.next_page_number %}
            ...
            <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
        {% endif %}
{% endif %}


{% endblock content %}

NewsPaper/templates/subscribe.html
{% extends 'default.html' %}
{% block content %}
    <h1 class="text-center">{{ message }}{{ category }}</h1>
{% endblock %}